version: '3'

services:
  web:
    image: nginx:latest
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - wordpress
    restart: on-failure

  db:
    image: mariadb:latest
    container_name: ${APP_NAME:?err}-mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?err}
      MYSQL_DATABASE: ${MARIADB_DATABASE:?err}
      MYSQL_USER: ${MARIADB_USER:?err}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD:?err}
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?err}
    ports:
      - '8084:80'
    depends_on:
      - db

  wordpress:
    image: wordpress
    container_name: ${APP_NAME:?err}-wordpress
    restart: always
    ports:
      - 8086:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MARIADB_USER:?err}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD:?err}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE:?err}
    volumes:
      - ./wordpress:/var/www/html